name: Generate Snake Animation

on:
  schedule: # Executa a cada 12h
    - cron: "0 */12 * * *"
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    name: Generate Snake Game
    runs-on: ubuntu-latest

    steps:
      - name: Instalar dependÃªncias do canvas
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev build-essential g++

      - name: Gerar github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: Joao4584
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Publicar snake no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
